// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cnuphfizhokzywhsvbln.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNudXBoZml6aG9renl3aHN2YmxuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA2NzczMjMsImV4cCI6MjA2NjI1MzMyM30.n_Ocmi-7727YQZNTrOI4fCNrg6wjF90F4e8HLceAacY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);